name: flutter_application_tugasbesar
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.7+3
  flutter_tts: ^3.5.0

  intl: ^0.19.0
  uuid: ^3.0.6
  pdf: ^3.11.1
  barcode_widget: ^2.0.4
  printing: ^5.12.0
  qr_flutter: ^4.0.0
  quickalert: ^1.1.0
  http: ^1.2.2
  flutter_riverpod: ^2.6.1
  flutter_neumorphic_plus: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
  
  fonts:
  - family: Roboto
    fonts:
    - asset: fonts/Roboto-Regular.ttf
    - asset: fonts/Roboto-Bold.ttf
      weight: 600

